### ISSUE TITLE
Panic when connecting through alloydb auth proxy - panic: runtime error: slice bounds out of range [:1157627904] with capacity 16384

### ISSUE THREAD

**Issue by andriihrachov** [GoogleCloudPlatform/alloydb-auth-proxy#504]
### Bug Description

alloydb proxy crashes with error, when deployed as a sidecar on kubernetes

```
2023/11/17 15:52:42 [********] accepted connection from 127.0.0.1:51470
panic: runtime error: slice bounds out of range [:1157627904] with capacity 16384
```

### Stacktrace

```bash
goroutine 9 [running]:
cloud.google.com/go/alloydbconn.(*Dialer).metadataExchange(0xc0000bf320, {0x12687f8?, 0xc000510000})
	/go/pkg/mod/cloud.google.com/go/alloydbconn@v1.5.0/dialer.go:337 +0x777
cloud.google.com/go/alloydbconn.(*Dialer).Dial(0xc0000bf320, {0x1263f08, 0xc0004cc000}, {0x7ffd5eaa8c14, 0x52}, {0x0, 0x0, 0x0?})
	/go/pkg/mod/cloud.google.com/go/alloydbconn@v1.5.0/dialer.go:247 +0xc34
github.com/GoogleCloudPlatform/alloydb-auth-proxy/internal/proxy.(*Client).serveSocketMount.func1()
	/go/src/alloydb-auth-proxy/internal/proxy/proxy.go:651 +0x2b1
created by github.com/GoogleCloudPlatform/alloydb-auth-proxy/internal/proxy.(*Client).serveSocketMount in goroutine 8
	/go/src/alloydb-auth-proxy/internal/proxy/proxy.go:631 +0x1da
```

### Steps to reproduce?

1. 1.5.0 version of gcr.io/alloydb-connectors/alloydb-auth-proxy
2. deploy on kubernetes as a sidecar
3. run psql to connect from a neighbor conatiner / port forward from local

### Environment

GKE

**Comment by enocom** [comment]
What region is your cluster in?

**Comment by enocom** [comment]
The new Go Connector version (and Proxy version) introduces a metadata exchange check prior to the database protocol taking over. You're seeing this panic because your instance doesn't understand the metadata exchange. This is not expected behavior.

Talking with some folks on the AlloyDB team, I'm told a recent rollout may have failed for a very small number of instances. Your instance seems to be one. If you have a support contract, you can open a ticket to get a fix sooner than the next rollout (tell them to cc me and I'll help get the right people to look at this). Otherwise, I'd suggest staying on v1.4.1 and I'll report back when I see the few stragglers fixed.

**Comment by andriihrachov** [comment]
> What region is your cluster in?

us-east4 

Thanks a lot, I downgraded to 1.4.1

**Comment by cthumuluru** [comment]
Can you point us to the time window when you saw these errors?

**Comment by andriihrachov** [comment]
17.11.2023 ~17:00 CET

**Comment by enocom** [comment]
FWIW I tested this on a newly created instance and didn't see any issues. It's possible some existing instances will be affected.

**Comment by andriihrachov** [comment]
thanks. it was test db anyway, so I'll recreate

**Comment by enocom** [comment]
FYI I've moved our `latest` container tags back to v1.4.1 for now too to try to minimize disruption.

**Comment by enocom** [comment]
Quick update here after digging into this a bit more. If anyone runs into this issue here's how to work around it:

- Downgrade to v1.4.1 which is unaffected.
- Consider updating any static database flag that requires a restart. Once the instance is restarted, it will correctly understand the metadata exchange and work with v1.5.0
- If you're still hitting this error, reach out to support for more help.

We expect this issue will be fully resolved during our next data plane rollout. Sorry for the inconvenience.

**Comment by StevenACoffman** [comment]
```
go mod edit -replace cloud.google.com/go/alloydbconn=cloud.google.com/go/alloydbconn@v1.4.1
go mod tidy
```

**Comment by enocom** [comment]
This has now been fixed in the latest rollout.

**Comment by tanvirp** [comment]
Looks like issue still exists with latest version as well. We have tried to restart the instances with no success.

```
panic: runtime error: slice bounds out of range [:1157627904] with capacity 16384

goroutine 59 [running]:
cloud.google.com/go/alloydbconn.(*Dialer).metadataExchange(0xc0000f2960, {0x13cba98?, 0xc0008482a0?}, {0x13d2d70, 0xc000850008}, 0x0)
	/go/pkg/mod/cloud.google.com/go/alloydbconn@v1.17.1/dialer.go:540 +0x6e5
cloud.google.com/go/alloydbconn.(*Dialer).Dial(0xc0000f2960, {0x13cbb40, 0xc0000d25b0}, {0xc0000460bd, 0x7d}, {0x0, 0x0, 0x0?})
	/go/pkg/mod/cloud.google.com/go/alloydbconn@v1.17.1/dialer.go:408 +0x1807
github.com/GoogleCloudPlatform/alloydb-auth-proxy/internal/proxy.(*Client).serveSocketMount.func1()
	/go/src/alloydb-auth-proxy/internal/proxy/proxy.go:740 +0x2a8
created by github.com/GoogleCloudPlatform/alloydb-auth-proxy/internal/proxy.(*Client).serveSocketMount in goroutine 51
	/go/src/alloydb-auth-proxy/internal/proxy/proxy.go:720 +0xd5
```
